### ISSUE TITLE
No Angler Fish Spawning, Wierd Texture On Screen, TPS Concerns

### ISSUE THREAD

**Issue by Boolyman** [Team-Rapture/Aquatic#3]
Hello,
Was speaking with Sora a bit last night and was looking forward to trying out the mod.  A couple things I noticed that I wanted to put in a ticket for, but I don't know if they are intended, or a bug.  I know this was put together in just a few days for modjam, and you guys did  a great job.  I look forward to using this in the future.

1) I know Angler fish are supposed to spawn.  I'm not getting any at all.  The entire dimension is empty.  But when I run a /tps profile to see where lag issues are coming from, there are 500+ entity calls listed for dimension 300.
2) Because you guys use a custom fluid to replace water... no other water creatures spawn in this dimension, which is a bit disspointing from a pack maker POV.  Im not sure what other mechanics might be affected by this difference in fluids.
3) There is an annoying texture across the screen when underwater in your dimension.  Its like blockey lines of light grey discoloration across the whole screen.  See attached picture.  
![2018-04-04 12_02_13-greenshot](https://user-images.githubusercontent.com/24765883/38328709-6f319642-3800-11e8-88a8-dea2d861b511.png)

**Comment by abused** [comment]
Hey,

` I know Angler fish are supposed to spawn. I'm not getting any at all. The entire dimension is empty. But when I run a /tps profile to see where lag issues are coming from, there are 500+ entity calls listed for dimension 300.`
I'm unsure why this is occurring i thought we have fixed the issue, apparently not, i'll go through in just a minute here and check this out

`Because you guys use a custom fluid to replace water... no other water creatures spawn in this dimension, which is a bit disspointing from a pack maker POV. Im not sure what other mechanics might be affected by this difference in fluids.`
This is essentially because we have a custom biome, with new biomes you have to specify what mobs you want to spawn there, what we can do maximum is either add the other mobs as an optional dependency and make their mobs spawn or add an api option for the mod makers to import and add their mobs to the list to spawn in our dimension

`There is an annoying texture across the screen when underwater in your dimension. Its like blockey lines of light grey discoloration across the whole screen. See attached picture.`
I believe that was intended as to make it seem as your in water as it is the water texture that's applied

**Comment by EPIICTHUNDERCAT** [comment]
Mobs should spawn, I was getting them just fine, however when the world is lagging it seems to skip their spawn, I got mob spawns a little after the world loaded in. ill doubke check the spawns but it should work

**Comment by EPIICTHUNDERCAT** [comment]
![2018-04-03_19 11 01](https://user-images.githubusercontent.com/19758921/38338063-cb60225a-381c-11e8-99e0-ac30e014b220.png)

my mobs spawns in my world.

**Comment by sekwah41** [comment]
The grey lines are rendered when you are in a Material.WATER block, ill take a look to see if there is a render event to cancel it when you have certain helmets on. I also know it cancels when you have water breathing potions (or at least im pretty sure it does)

**Comment by sekwah41** [comment]
Just pushed code for allowing scuba helmet to stop that texture from rendering 

https://github.com/Team-Rapture/Aquatic/commit/c64e0508a7a161752d58926b84ad2f6acf2484c2

**Comment by Boolyman** [comment]
Awesome work guys, thanks!

**Comment by UpcraftLP** [comment]
fixed the spawns recently, and don't worry, TPS will be improved once we have the final world generator in place
